### ISSUE TITLE
lJTSImageViewController library not found & Naming collision detected

### ISSUE THREAD

**Issue by yarnball** [fangwei716/30-days-of-react-native#2]
Hi,

Looks like nice work with this.

I've followed your instructions, but I've run into an issue (seems like it was mentioned before- but I'm using the latest repo & having the issue). I've done theses steps.

1. git clone https://github.com/fangwei716/30-days-of-react-native.git 30DAYS
2. cd 30DAYS
3. npm install
4. cd ios
5. pod install (if I skip this step, I get the 'RCTBridge.h  not found")

Open: the '.xcodeproj' file gives me this error:

```ld: warning: directory not found for option '-L/Users/mac1/Dev/React/React30/ios/build/Debug-iphoneos'
ld: library not found for -lJTSImageViewController```

Opening the '.xcworkspace' file gives me this error:

```Failed to build DependencyGraph: Naming collision detected: /Users/mac1/Dev/React/React30/node_modules/react/node_modules/fbjs/lib/warning.js collides with /Users/mac1/Dev/React/React30/node_modules/react-native/node_modules/fbjs/lib/warning.js
Error: Naming collision detected: /Users/mac1/Dev/React/React30/node_modules/react/node_modules/fbjs/lib/warning.js collides with /Users/mac1/Dev/React/React30/node_modules/react-native/node_modules/fbjs/lib/warning.js
    at HasteMap._updateHasteMap (HasteMap.js:132:13)
    at HasteMap.js:103:28
    at tryCallOne (/Users/mac1/Dev/React/React30/node_modules/react-native/node_modules/promise/lib/core.js:37:12)
    at /Users/mac1/Dev/React/React30/node_modules/react-native/node_modules/promise/lib/core.js:123:15
    at flush (/Users/mac1/Dev/React/React30/node_modules/react-native/node_modules/promise/node_modules/asap/raw.js:50:29)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)```


Running 'react run-ios' gives me this error:

```/Users/mac1/Dev/React/React30/node_modules/react-native/node_modules/promise/lib/done.js:10
      throw err;
      ^

Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/ThirtyDaysOfReactNative.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:464:13)
    at Object.execFileSync (child_process.js:484:13)
    at _runIOS (runIOS.js:77:34)
    at runIOS.js:24:5
    at tryCallTwo (/Users/mac1/Dev/React/React30/node_modules/react-native/node_modules/promise/lib/core.js:45:5)
    at doResolve (/Users/mac1/Dev/React/React30/node_modules/react-native/node_modules/promise/lib/core.js:200:13)
    at new Promise (/Users/mac1/Dev/React/React30/node_modules/react-native/node_modules/promise/lib/core.js:66:3)
    at Array.runIOS (runIOS.js:23:10)
    at Object.run (/Users/mac1/Dev/React/React30/node_modules/react-native/local-cli/cli.js:86:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-native-cli/index.js:88:7)```

**Comment by fangwei716** [comment]
This error never happens to me. Try to delete node_modules folder inside /Users/mac1/Dev/React/React30/node_modules/react-native/ and rerun from  '.xcworkspace' file.

**Comment by yarnball** [comment]
I removed "node_modules" and ran the .xcworkspace file. I still get the "RCTRootView.h" file not found error.

**Comment by fangwei716** [comment]
not sure why but I google it, it seems that npm install can solve this issue. Make sure npm install on the React30 folder.

**Comment by yarnball** [comment]
Ok it builds now- but getting the Name collisions detected error:

```Failed to build DependencyGraph: Naming collision detected: /Users/mac1/Dev/React/React30/node_modules/react/node_modules/fbjs/lib/warning.js collides with /Users/mac1/Dev/React/React30/node_modules/react-native/node_modules/fbjs/lib/warning.js
Error: Naming collision detected: /Users/mac1/Dev/React/React30/node_modules/react/node_modules/fbjs/lib/warning.js collides with /Users/mac1/Dev/React/React30/node_modules/react-native/node_modules/fbjs/lib/warning.js
    at HasteMap._updateHasteMap (HasteMap.js:132:13)
    at HasteMap.js:103:28
    at tryCallOne (/Users/mac1/Dev/React/React30/node_modules/react-native/node_modules/promise/lib/core.js:37:12)
    at /Users/mac1/Dev/React/React30/node_modules/react-native/node_modules/promise/lib/core.js:123:15
    at flush (/Users/mac1/Dev/React/React30/node_modules/react-native/node_modules/promise/node_modules/asap/raw.js:50:29)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)```

**Comment by fangwei716** [comment]
should not have /Users/mac1/Dev/React/React30/node_modules/react/node_modules folder. The only node_modules folder is under React30. Delete it? Also node_modules/promise/node_modules

**Comment by yarnball** [comment]
Ok- I deleted "/Users/mac1/Dev/React/React30/node_modules/react/node_modules".

I have noticed- there are 'node_modules' folders inside of '/Users/mac1/Dev/React/React30/node_modules/react-native/' and a few other folders. Do I need to remove all of them?

Also- I do not have a folder called 'promise'. Is your last comment saying to delete it?

**Comment by fangwei716** [comment]
I think you do. In the error message, it says... /Users/mac1/Dev/React/React30/node_modules/react-native/node_modules/promise/node_modules/asap/raw.js. Delete the node_modules under promise.

**Comment by yarnball** [comment]
Looks like it need that module: 

```Error: Cannot find module 'asap/raw'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/mac1/Dev/React/React30/node_modules/react-native/node_modules/promise/lib/core.js:3:12)
    at Module._compile (module.js:409:26)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/mac1/Dev/React/React30/node_modules/react-native/node_modules/babel-register/lib/node.js:138:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)```

**Comment by fangwei716** [comment]
Then I guess you can't delete that.  If it still doesn't work, you can try to redo the process. Since you have installed cocoapods. Just git clone and npm install in the right folder. It works fine last time I tested.
