### ISSUE TITLE
Failed to build DependencyGraph: Naming collision detected:

### ISSUE THREAD

**Issue by liangz168** [fangwei716/30-days-of-react-native#8]
我运行的时候报这个错是什么情况？
[21:00:00] <START> find dependencies
Failed to build DependencyGraph: Naming collision detected: /Users/weiliang/Documents/work/react/react-native/30days/node_modules/react/lib/update.js collides with /Users/weiliang/Documents/work/react/react-native/30days/node_modules/react-native/node_modules/react/lib/update.js
Error: Naming collision detected: /Users/weiliang/Documents/work/react/react-native/30days/node_modules/react/lib/update.js collides with /Users/weiliang/Documents/work/react/react-native/30days/node_modules/react-native/node_modules/react/lib/update.js
    at HasteMap._updateHasteMap (HasteMap.js:132:13)
    at HasteMap.js:103:28
    at tryCallOne (/Users/weiliang/Documents/work/react/react-native/30days/node_modules/react-native/node_modules/promise/lib/core.js:37:12)
    at /Users/weiliang/Documents/work/react/react-native/30days/node_modules/react-native/node_modules/promise/lib/core.js:123:15
    at flush (/Users/weiliang/Documents/work/react/react-native/30days/node_modules/react-native/node_modules/promise/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)
~
Process terminated. Press <enter> to close the window

**Comment by fangwei716** [comment]
using node.js 5.x should fix this issue.

**Comment by liangz168** [comment]
@fangwei716  Great! It works.
